### ISSUE TITLE
Create compress module using libvips 

### ISSUE THREAD

**Issue by addityasingh** [optimal-image/optimal-image#13]
Create compress module using libvips as ffi. this is needed to compress the images to different quality levels needed before comparison

Reference:
http://code.flickr.net/2015/09/25/perceptual-image-compression-at-flickr/

**Comment by axyz** [comment]
@addityasingh cool, ping me if you have issues with the C side, I played around a bit with vips and there are some not immediately intuitive concepts, but docs are pretty good

**Comment by addityasingh** [comment]
I am checking it from here (http://jcupitt.github.io/libvips/API/current/). Is this the one or something else?

**Comment by addityasingh** [comment]
Closed as part of #15
