### ISSUE TITLE
Create module to generate 5 compressed variants of every image

### ISSUE THREAD

**Issue by addityasingh** [optimal-image/optimal-image#3]
We need to create a module (or possibly an independent library) to generate compressed variants of every image. To begin with we can start with generating 5(log30 base 2) from compression **Quality** _70-100_

**Comment by addityasingh** [comment]
@axyz Check and update if I missed anything from our discussion

**Comment by axyz** [comment]
search implemented in https://github.com/optimal-image/optimal-image/pull/16
